// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXaPgasUv35gYuRsT7j4PTqxB1A8FX_rA',
    appId: '1:265976870176:web:7ce1679a55448c64611345',
    messagingSenderId: '265976870176',
    projectId: 'flutter-crud-8d277',
    authDomain: 'flutter-crud-8d277.firebaseapp.com',
    databaseURL: 'https://flutter-crud-8d277-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-8d277.appspot.com',
    measurementId: 'G-75QDZKFQP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJyI3Pv9nlaQ7t3FUS5TUZNpbi-cvmhvc',
    appId: '1:265976870176:android:3bc02280e9e89223611345',
    messagingSenderId: '265976870176',
    projectId: 'flutter-crud-8d277',
    databaseURL: 'https://flutter-crud-8d277-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-8d277.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW8HasITubrdpDN2KrUg31cKv1C0d4HtM',
    appId: '1:265976870176:ios:7d6001ae9c15eaf6611345',
    messagingSenderId: '265976870176',
    projectId: 'flutter-crud-8d277',
    databaseURL: 'https://flutter-crud-8d277-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-8d277.appspot.com',
    iosClientId: '265976870176-ulcvle18borqvjhkmbpl6odvfd4u9bpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW8HasITubrdpDN2KrUg31cKv1C0d4HtM',
    appId: '1:265976870176:ios:7d6001ae9c15eaf6611345',
    messagingSenderId: '265976870176',
    projectId: 'flutter-crud-8d277',
    databaseURL: 'https://flutter-crud-8d277-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-8d277.appspot.com',
    iosClientId: '265976870176-ulcvle18borqvjhkmbpl6odvfd4u9bpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
